### ISSUE TITLE
ContractInstantiationFailed on factory function

### ISSUE THREAD

**Issue by ganesh1997oli** [swanky-dapps/marketplace#15]
Even though I have set contract has, it continuously gives `ContractInstantiationFailed ` issue. Anybody could you please help me?

<img width="1427" alt="Screenshot 2023-03-23 at 12 47 44" src="https://user-images.githubusercontent.com/42571338/227127989-ffaf4351-ea74-41f9-b431-08b098ff677b.png">
<img width="1427" alt="Screenshot 2023-03-23 at 12 48 00" src="https://user-images.githubusercontent.com/42571338/227128007-ba6a8f13-4c51-4498-858b-0c951c57889d.png">

**Comment by bobo-k2** [comment]
Hi, most likely hash you provided is wrong. Open your contract json (ABI) file and look for the `source.hash` value

<img width="608" alt="image" src="https://user-images.githubusercontent.com/8452361/227260196-afc26b63-7ffc-42de-9a31-9b4399bad73b.png">

**Comment by ganesh1997oli** [comment]
> Hi, most likely hash you provided is wrong. Open your contract json (ABI) file and look for the `source.hash` value
> 
> <img alt="image" width="608" src="https://user-images.githubusercontent.com/8452361/227260196-afc26b63-7ffc-42de-9a31-9b4399bad73b.png">

he @bobo-k2 thanks for quick response. I did exactly same copied hash from contract json(ABI) from `source.hash` 

<img width="1427" alt="Screenshot 2023-03-24 at 07 26 58" src="https://user-images.githubusercontent.com/42571338/227403122-7b7dd32d-7514-438f-83b9-82cd154df448.png">
