### ISSUE TITLE
ERROR: Cannot infer the root project id

### ISSUE THREAD

**Issue by ganesh1997oli** [swanky-dapps/marketplace#3]
With this configuration, aren't we supposed to deploy contract from root directory using `cargo contract build`? rather it throws error.

<img width="1395" alt="Screenshot 2022-12-18 at 15 42 31" src="https://user-images.githubusercontent.com/42571338/208291982-b8e193a2-8834-4cf7-8852-581f36d643f0.png">

**Comment by bobo-k2** [comment]
Since there are multiple contracts in the project you should build from a contract folder. This project is still under heavy development. After we merge https://github.com/swanky-dapps/marketplace/pull/4 please check the project again.

**Comment by vikiival** [comment]
```
➜  marketplace git:(main) cd contracts
➜  contracts git:(main) cargo contract build
ERROR: Loading Cargo.toml

Caused by:
    No such file or directory (os error 2)
➜  contracts git:(main)
```

**Comment by vikiival** [comment]
@bobo-k2 is it possible to solve this issue? 

it is blocker for me

**Comment by vikiival** [comment]
cc @Maar-io

**Comment by bobo-k2** [comment]
@vikiival. From the project root do the following:
```
cd contracts
cd marketplace
cargo contract build
```
