### ISSUE TITLE
Unable to Init smart contract via factory

### ISSUE THREAD

**Issue by vikiival** [swanky-dapps/marketplace#8]
I have problems with calling `factory` function on the marketplace contract.

I though first time that I did not set contract hash but the error is still there.

Built with latest main at hash 0xedf9dde8b7c52a23ef3972268217a92f3c356707388aaa68a3952e31973797c3

Failed Txs
https://shibuya.subscan.io/account/Z7rYZFFCFt9B2cv692TSWnxTKM1CYnoukBhxUd39ajsYWTe

Example of call:

![Screenshot 2023-01-23 at 13 28 21](https://user-images.githubusercontent.com/22471030/214039780-815d595b-5de4-4445-b04c-5a56f964c81e.png)

The supplied hash of RMRK smart contract 

0xd22f1aabf3d04bfba1ef5d0b5a5e1fa4764df7224afd1ee1422a8344a54b490f

**Comment by bobo-k2** [comment]
At the moment you can't create RMRK through factory. Only Shiden34 (https://github.com/swanky-dapps/nft)

**Comment by vikiival** [comment]
@Maar-io what is the desired outcome?
